from enum import Enum
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class DocumentArchetype(str, Enum):
    RESUME = "resume"
    REPORT = "report"
    INVOICE = "invoice"
    ATTENDANCE = "attendance"
    SPREADSHEET = "spreadsheet"
    FORMAL_LETTER = "formal_letter"
    PRD = "prd"
    GENERAL = "general"


class TableData(BaseModel):
    headers: List[str] = Field(default_factory=list)
    rows: List[List[str]] = Field(default_factory=list)
    alignment: List[str] = Field(default_factory=list)  # "left", "center", "right"
    col_widths: Optional[List[float]] = None
    summary_row: Optional[List[str]] = None


class CalloutBlock(BaseModel):
    title: str = "Note"
    content: str
    style: str = "info"  # "info", "warning", "success", "quote"


class DocumentSection(BaseModel):
    heading: str
    subheading: Optional[str] = None
    content_paragraphs: List[str] = Field(default_factory=list)
    bullet_points: List[str] = Field(default_factory=list)
    table: Optional[TableData] = None
    callouts: List[CalloutBlock] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)


class DocumentSpec(BaseModel):
    title: str
    subtitle: Optional[str] = None
    archetype: DocumentArchetype = DocumentArchetype.GENERAL
    author: Optional[str] = None
    organization: Optional[str] = None
    date_str: Optional[str] = None
    version: Optional[str] = None
    summary_box: Optional[str] = None
    key_metrics: Dict[str, str] = Field(default_factory=dict)
    contact_info: Dict[str, str] = Field(default_factory=dict)
    sections: List[DocumentSection] = Field(default_factory=list)
    footer_text: Optional[str] = "Generated by Aetherius AI • Confidential & Proprietary"
    accent_color: str = "#1E3A8A"  # Deep Corporate Blue
