import io
import re
from typing import List, Optional
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    KeepTogether,
    HRFlowable,
)
from reportlab.pdfgen import canvas
from backend.app.services.generators.document_models import DocumentSpec, DocumentArchetype, TableData


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to compute and render total page count ('Page X of Y')
    along with corporate headers and footers on every page.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748B"))

        # Footer
        footer_text = "Generated by Aetherius AI • Confidential & Verified"
        page_str = f"Page {self._pageNumber} of {page_count}"
        
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(40, 40, letter[0] - 40, 40)
        
        self.drawString(40, 28, footer_text)
        self.drawRightString(letter[0] - 40, 28, page_str)

        # Header (Pages > 1)
        if self._pageNumber > 1:
            self.drawString(40, letter[1] - 30, getattr(self, "doc_title", "Aetherius Report"))
            self.setStrokeColor(colors.HexColor("#E2E8F0"))
            self.setLineWidth(0.5)
            self.line(40, letter[1] - 35, letter[0] - 40, letter[1] - 35)

        self.restoreState()


class PDFGenerator:
    """
    Professional PDF generation engine utilizing ReportLab Flowables.
    Renders custom visual layouts tailored to student resumes, attendance reports,
    formal letters, invoices, and executive whitepapers.
    """

    @classmethod
    def generate_pdf_bytes(cls, spec: DocumentSpec) -> bytes:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=40,
            rightMargin=40,
            topMargin=45,
            bottomMargin=50,
            title=spec.title
        )

        styles = getSampleStyleSheet()
        accent = colors.HexColor(spec.accent_color)
        dark_text = colors.HexColor("#0F172A")
        muted_text = colors.HexColor("#475569")
        light_bg = colors.HexColor("#F8FAFC")
        border_color = colors.HexColor("#E2E8F0")

        # Custom Typographical Styles
        title_style = ParagraphStyle(
            "DocTitle",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=22,
            leading=26,
            textColor=dark_text,
            spaceAfter=4,
        )

        subtitle_style = ParagraphStyle(
            "DocSubtitle",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=11,
            leading=15,
            textColor=muted_text,
            spaceAfter=12,
        )

        h1_style = ParagraphStyle(
            "SectionH1",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=13,
            leading=17,
            textColor=accent,
            spaceBefore=14,
            spaceAfter=6,
            keepWithNext=True,
        )

        body_style = ParagraphStyle(
            "DocBody",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9.5,
            leading=13.5,
            textColor=dark_text,
            spaceAfter=6,
        )

        bullet_style = ParagraphStyle(
            "DocBullet",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9.5,
            leading=13.5,
            textColor=dark_text,
            leftIndent=14,
            firstLineIndent=-10,
            spaceAfter=4,
        )

        callout_style = ParagraphStyle(
            "DocCallout",
            parent=styles["Normal"],
            fontName="Helvetica-Oblique",
            fontSize=9,
            leading=13,
            textColor=colors.HexColor("#1E293B"),
        )

        table_cell_style = ParagraphStyle(
            "TableCell",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=8.5,
            leading=11.5,
            textColor=dark_text,
        )

        table_header_style = ParagraphStyle(
            "TableHeader",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=8.5,
            leading=11.5,
            textColor=colors.white,
        )

        story = []

        # 1. Header Banner & Title
        story.append(Paragraph(spec.title, title_style))
        if spec.subtitle:
            story.append(Paragraph(spec.subtitle, subtitle_style))
        
        # Meta info bar (Date, Author, Document Archetype)
        meta_items = []
        if spec.date_str:
            meta_items.append(f"<b>Date:</b> {spec.date_str}")
        if spec.author:
            meta_items.append(f"<b>Prepared By:</b> {spec.author}")
        if spec.archetype:
            meta_items.append(f"<b>Type:</b> {spec.archetype.value.replace('_', ' ').title()}")

        meta_p = Paragraph(" &nbsp;&nbsp;|&nbsp;&nbsp; ".join(meta_items), subtitle_style)
        story.append(meta_p)
        story.append(HRFlowable(width="100%", thickness=1.5, color=accent, spaceBefore=4, spaceAfter=12))

        # 2. Key Metrics Bar (if present)
        if spec.key_metrics:
            metric_data = []
            m_headers = []
            m_vals = []
            for k, v in list(spec.key_metrics.items())[:4]:
                m_headers.append(Paragraph(f"<b>{k}</b>", table_header_style))
                m_vals.append(Paragraph(f"<b>{v}</b>", title_style))
            
            metric_table = Table([m_headers, m_vals], colWidths=[(doc.width / len(m_headers))] * len(m_headers))
            metric_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), accent),
                ("BACKGROUND", (0, 1), (-1, 1), light_bg),
                ("ALIGN", (0, 0), (-1, -1), "CENTER"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("BOX", (0, 0), (-1, -1), 1, border_color),
                ("INNERGRID", (0, 0), (-1, -1), 0.5, border_color),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]))
            story.append(metric_table)
            story.append(Spacer(1, 12))

        # 3. Render Document Sections
        for section in spec.sections:
            if section.heading:
                story.append(Paragraph(section.heading, h1_style))
                story.append(HRFlowable(width="100%", thickness=0.5, color=border_color, spaceBefore=1, spaceAfter=6))

            # Paragraphs
            for p_text in section.content_paragraphs:
                # Convert markdown **bold** to <b>bold</b>
                clean_html = re.sub(r"\*\*(.*?)\*\*", r"<b>\1</b>", p_text)
                clean_html = re.sub(r"\*(.*?)\*", r"<i>\1</i>", clean_html)
                clean_html = re.sub(r"`(.*?)`", r"<font face='Courier'>\1</font>", clean_html)
                story.append(Paragraph(clean_html, body_style))

            # Bullets
            for b_text in section.bullet_points:
                clean_b = re.sub(r"\*\*(.*?)\*\*", r"<b>\1</b>", b_text)
                clean_b = re.sub(r"\*(.*?)\*", r"<i>\1</i>", clean_b)
                story.append(Paragraph(f"&bull; {clean_b}", bullet_style))

            # Callouts
            for callout in section.callouts:
                c_p = Paragraph(f"<b>{callout.title}:</b> {callout.content}", callout_style)
                c_table = Table([[c_p]], colWidths=[doc.width])
                c_table.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F1F5F9")),
                    ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
                    ("LEFTPADDING", (0, 0), (-1, -1), 12),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 12),
                    ("TOPPADDING", (0, 0), (-1, -1), 8),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ]))
                story.append(Spacer(1, 4))
                story.append(c_table)
                story.append(Spacer(1, 6))

            # Structured Data Table
            if section.table and section.table.headers:
                t_data = []
                # Header row
                h_row = [Paragraph(f"<b>{h}</b>", table_header_style) for h in section.table.headers]
                t_data.append(h_row)

                # Data rows
                for r_idx, row in enumerate(section.table.rows):
                    r_cells = []
                    for c_idx, cell in enumerate(row):
                        cell_clean = re.sub(r"\*\*(.*?)\*\*", r"<b>\1</b>", str(cell))
                        r_cells.append(Paragraph(cell_clean, table_cell_style))
                    # Fill missing cells
                    while len(r_cells) < len(section.table.headers):
                        r_cells.append(Paragraph("", table_cell_style))
                    t_data.append(r_cells[:len(section.table.headers)])

                col_w = doc.width / len(section.table.headers)
                report_table = Table(t_data, colWidths=[col_w] * len(section.table.headers), repeatRows=1)
                report_table.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, 0), accent),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                    ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, light_bg]),
                    ("GRID", (0, 0), (-1, -1), 0.5, border_color),
                    ("TOPPADDING", (0, 0), (-1, -1), 5),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
                    ("LEFTPADDING", (0, 0), (-1, -1), 6),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ]))
                story.append(Spacer(1, 6))
                story.append(report_table)
                story.append(Spacer(1, 8))

            story.append(Spacer(1, 6))

        # Build PDF using NumberedCanvas
        doc.build(story, canvasmaker=NumberedCanvas)
        return buffer.getvalue()
